name = "jimbridger-dev"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-25"

# top level for production
[[kv_namespaces]]
binding = "CACHE"
id = "8a29fcc28a964ad1af06df234507e1c7"

# local/preview
[[env.preview.kv_namespaces]]
binding = "CACHE"
id = "test"
