name = "jimbridger-dev"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-01-25"

# top level for production
[[kv_namespaces]]
binding = "CACHE"
id = "8a29fcc28a964ad1af06df234507e1c7"

[[kv_namespaces]]
binding = "KV_SHEETS"
id = "e103a04c1dba4d83bf5ceb2cc3c4b1ed"
remote = true
